server.port=8080

spring.application.name=library-management-system
jwt.secret=your-very-long-secret-key-that-is-at-least-32-characters-long
jwt.expiration=3600000

database.url=jdbc:mysql://localhost/lms
database.username=root
database.password=Xias